export {
  Skeleton,
  SkeletonText,
  SkeletonHeading,
  SkeletonAvatar,
  SkeletonButton,
  SkeletonImage,
  SkeletonCard,
  SkeletonArticle,
  SkeletonProfile,
  SkeletonTable,
  SkeletonGrid,
  ImagePlaceholder,
  Loader,
  PageLoader,
  type SkeletonAnimation,
  type LoaderVariant,
  type LoaderSize,
} from "./skeleton";
