/**
 * UI Utilities
 *
 * SelectOption generators and pre-built option arrays for UI components.
 */

export {
  // Types
  type SelectOption,
  // Generator functions
  generateOptionsFromScale,
  generateOptionsFromObject,
  // Spacing
  SPACING_OPTIONS,
  EXTENDED_SPACING_OPTIONS,
  GAP_OPTIONS,
  // Borders
  BORDER_WIDTH_OPTIONS,
  BORDER_STYLE_OPTIONS,
  BORDER_RADIUS_OPTIONS,
  // Shadows
  SHADOW_OPTIONS,
  // Layout
  SECTION_WIDTH_OPTIONS,
  CONTAINER_WIDTH_OPTIONS,
  SECTION_MIN_HEIGHT_OPTIONS,
  CONTAINER_MIN_HEIGHT_OPTIONS,
  OVERFLOW_OPTIONS,
  // Flex/Grid
  DIRECTION_OPTIONS,
  JUSTIFY_OPTIONS,
  ALIGN_OPTIONS,
  GRID_COLUMNS_OPTIONS,
  // Background
  BACKGROUND_TYPE_OPTIONS,
  BACKGROUND_PRESET_OPTIONS,
  GRADIENT_TYPE_OPTIONS,
  BACKGROUND_SIZE_OPTIONS,
  BACKGROUND_POSITION_OPTIONS,
  // Typography
  HEADING_LEVEL_OPTIONS,
  TEXT_ALIGN_OPTIONS,
  FONT_SIZE_OPTIONS,
  FONT_WEIGHT_OPTIONS,
} from "./select-options";
