export {
  Text,
  type TextProps,
  type TextElement,
  type TextSize,
  type TextVariant,
  type FontWeight,
  type TextAlign,
  type LetterSpacing,
  type LineHeight,
  type FontStyle,
  type TextTransform,
  type TextDecoration,
  type WhiteSpace,
  type MaxWidthPreset,
  type Columns,
  type ColumnGap,
  type OpacityPreset,
  type ColorPreset,
} from "./text";
